;vcp-Command  supported  discrete  vcp-cmdInUse
; where
;   vcp-Command = standard vcp command code
;   supported = 0 if unsupported, 1 if supported
;   discrete = 0 for Continuous, 1 for Discrete
;   vcp-cmdInUse = vendor specific vcp command, same if follows standard, else different if non-standard
; 
00 0 0 00   
01 0 0 01 Degauss
02 1 0 02 
03 0 0 03 
04 1 0 04 Restore Factory Defaults
05 1 0 05 Restore Brightness and Contast Defaults
06 1 0 06 Restore Factory Geometry Defaults 
07 0 0 07 
08 1 0 08 Restore Factory Color Defaults 
09 0 0 09 
0A 0 0 0A Restore factory TV defaults
0B 1 0 0B 
0C 1 0 0C Color temperature request
0D 0 0 0D 
0E 1 0 0E CLOCK
0F 0 0 0F 
10 1 0 10 Brightness
11 0 0 11 
12 1 0 12 Contrast
13 0 0 13 
14 1 1 14 Select Color Preset (01h = sRGB) (White Point)
15 0 0 15 
16 1 0 16 Red Video Gain
17 0 0 17 
18 1 0 18 Green Video Gain
19 0 0 19 
1A 1 0 1A Blue Video Gain
1B 0 0 1B 
1C 0 0 1C Focus
1D 0 0 1D 
1E 1 0 1E Auto Setup (Auto Reset)
1F 1 0 1F 
20 1 0 20 Horizontal Position
21 0 0 21 
22 0 0 22 Horizontal Size
23 0 0 23 
24 0 0 24 Horizontal Pincushion
25 0 0 25 
26 0 0 26 Horizontal Pincushion Balance
27 0 0 27 
28 0 0 28 Horizontal Misconvergence
29 0 0 29 
2A 0 0 2A Horizontal Linearity
2B 0 0 2B 
2C 0 0 2C Horizontal Linearity balance
2D 0 0 2D 
2E 0 0 2E 
2F 0 0 2F 
30 1 0 30 Vertical Position
31 0 0 31 
32 0 0 32 Vertical Size
33 0 0 33 
34 0 0 34 Vertical pincushion
35 0 0 35 
36 0 0 36 Vertical pincushion balance
37 0 0 37 
38 0 0 38 Vertical Misconvergence
39 0 0 39 
3A 0 0 3A Vertical Linearity
3B 0 0 3B 
3C 0 0 3C Vertical Linearity Balance
3D 0 0 3D 
3E 1 0 3E CLOCK PHASE
3F 0 0 3F 
40 0 0 40 Key Balance
41 0 0 41 
42 0 0 42 Horizontal Trapezoidal Distortion
43 0 0 43 Vertical Trapezoidal Distortion
44 0 0 44 Tilt(Rotation)
45 0 0 45 
46 0 0 46 Top Corner Distortion
47 0 0 47 
48 0 0 48 Top Corner Distortion Balance
49 0 0 49 
4A 0 0 4A Bottom Corner Distortion
4B 0 0 4B 
4C 0 0 4C Bottom Corner Distortion Balance
4D 0 0 4D 
4E 0 0 4E Trapezoid
4F 0 0 4F 
50 0 0 50 Keystone
51 0 0 51 
52 1 0 52 
53 0 0 53 
54 0 0 54 
55 0 0 55 
56 0 0 56 Horizontal Moire
57 0 0 57 
58 0 0 58 Vertical Moire
59 0 0 59 
5A 0 0 5A 
5B 0 0 5B 
5C 0 0 5C 
5D 0 0 5D 
5E 0 0 5E 
5F 0 0 5F 
60 1 0 60 Input source
61 0 0 61 
62 1 0 62 Audio Speaker Volume
63 0 0 63 
64 0 0 64 Audio Microphone Volume
65 0 0 65 
66 0 0 66 
67 0 0 67 
68 0 0 68 
69 0 0 69 
6A 0 0 6A 
6B 0 0 6B 
6C 1 0 6C Red Video Black Level
6D 0 0 6D 
6E 1 0 6E Green Video Black Level
6F 0 0 6F 
70 1 0 70 Blue Video Black Level
71 0 0 71 
72 0 0 72 
73 0 0 73 
74 0 0 74 
75 0 0 75 
76 0 0 76 
77 0 0 77 
78 0 0 78 
79 0 0 79 
7A 0 0 7A Adjust focal plane
7B 0 0 7B 
7C 0 0 7C Adjust zoom
7D 0 0 7D 
7E 0 0 7E 
7F 0 0 7F 
80 0 0 80 
81 0 0 81 
82 0 0 82 Horizontal flip
83 0 0 83 
84 0 0 84 Vertical flip
85 0 0 85 
86 1 0 86 Display scaling
87 0 0 87 
88 0 0 88 Velocity scan modulation
89 0 0 89 
8A 0 0 8A TV Color Saturation
8B 0 0 8B TV-Channel UP/DOWN
8C 0 0 8C TV-Sharpness
8D 1 0 8D TV-Audio Mute
8E 0 0 8E TV contrast
8F 0 0 8F TV-Audio Control(Treble)
90 0 0 90 TV-HUE(Tint)
91 0 0 91 TV-Audio Control (Bass)
92 0 0 92 TV-Black Level/Brightness
93 0 0 93 TV-Audio Control(Balance)
94 0 0 94 Audio: stereo mode
95 0 0 95 window position(TL_X)
96 0 0 96 window position(TL_Y)
97 0 0 97 window position(BR_X)
98 0 0 98 window position(BR_Y)
99 0 0 99 Window Control ON/OFF
9A 0 0 9A Window BackGround
9B 0 0 9B 6 Axis color control RED
9C 0 0 9C 6 Axis color control YELLOW
9D 0 0 9D 6 Axis color control GREEN
9E 0 0 9E 6 Axis color control CYAN
9F 0 0 9F 6 Axis color control BLUE
A0 0 0 A0 6 Axis color control MAGENTA
A1 0 0 A1 
A2 0 0 A2 Auto SetUp ON/OFF
A3 0 0 A3 
A4 0 0 A4 
A5 0 0 A5 
A6 0 0 A6 
A7 0 0 A7 
A8 0 0 A8 
A9 0 0 A9 
AA 0 0 AA Screen Orientation
AB 0 0 AB 
AC 1 0 AC Horizontal frequency
AD 0 0 AD 
AE 1 0 AE Vertical frequency
AF 0 0 AF 
B0 0 0 B0 
B1 0 0 B1 
B2 1 0 B2 Flat panel sub-pixel pattern
B3 0 0 B3 
B4 0 0 B4 Flat panel RGB_ordering
B5 0 0 B5 
B6 1 0 B6 Monitor Display technology type
B7 0 0 B7 DPVL Protocol Mode
B8 0 0 B8 DPVL Protocol Parameter
B9 0 0 B9 DPVL Monitor X Origin
BA 0 0 BA DPVL Monitor Y Origin
BB 0 0 BB DPVL Unrecoverable error count
BC 0 0 BC DPVL Recoverable error count
BD 0 0 BD 
BE 0 0 BE 
BF 0 0 BF 
C0 1 0 C0 
C1 0 0 C1 
C2 0 0 C2 
C3 0 0 C3 
C4 0 0 C4 
C5 0 0 C5 
C6 1 0 C6 
C7 0 0 C7 
C8 1 0 C8 
C9 1 0 C9 
CA 1 0 CA OSD
CB 0 0 CB 
CC 0 0 CC 
CD 0 0 CD 
CE 0 0 CE 
CF 0 0 CF 
D0 0 0 D0 Output selection
D1 0 0 D1 
D2 0 0 D2 
D3 0 0 D3 
D4 0 0 D4 Stereo video mode
D5 0 0 D5 
D6 1 0 D6 Power Mode
D7 0 0 D7 
D8 0 0 D8 
D9 0 0 D9 
DA 0 0 DA Scan format
DB 0 0 DB 
DC 0 0 DC Display Mode
DD 0 0 DD 
DE 0 0 DE Operation mode
DF 1 0 DF VCP Version
E0 0 0 E0 Vendor Specific Control
E1 0 0 E1 Vendor Specific Control
E2 0 0 E2 Vendor Specific Control
E3 0 0 E3 Vendor Specific Control
E4 0 0 E4 Vendor Specific Control
E5 0 0 E5 Vendor Specific Control
E6 0 0 E6 Vendor Specific Control
E7 0 0 E7 Vendor Specific Control
E8 0 0 E8 Vendor Specific Control
E9 0 0 E9 Vendor Specific Control
EA 0 0 EA Vendor Specific Control
EB 0 0 EB Vendor Specific Control
EC 0 0 EC Vendor Specific Control
ED 0 0 ED Vendor Specific Control
EE 0 0 EE Vendor Specific Control
EF 0 0 EF Vendor Specific Control
F0 0 0 F0 Vendor Specific Control
F1 0 0 F1 Vendor Specific Control
F2 0 0 F2 Vendor Specific Control
F3 0 0 F3 Vendor Specific Control
F4 0 0 F4 Vendor Specific Control
F5 0 0 F5 Vendor Specific Control
F6 0 0 F6 Vendor Specific Control
F7 0 0 F7 Vendor Specific Control
F8 0 0 F8 Vendor Specific Control
F9 0 0 F9 Vendor Specific Control
FA 1 1 FA Vendor Specific Control
FB 1 0 FB Vendor Specific Control
FC 1 1 FC Vendor Specific Control
FD 1 1 FD Vendor Specific Control
FE 1 1 FE Vendor Specific Control
FF 0 0 FF Vendor Specific Control
